### ISSUE TITLE
Unused generated schema variable

### ISSUE THREAD

**Issue by Nargonath** [protojour/migrado#9]
I wrote a `schema.yml` file:

```yaml
all: &all
  _id:
    type: string
    readOnly: true
  _key:
    type: string
    readOnly: true
  _rev:
    type: string
    readOnly: true

edges: &edges
  _from:
    type: string
  _to:
    type: string

collections:
  MyCollection:
    type: object
    properties:
      <<: *all
      id:
        type: string
      propOne:
        type: string
      propTwo:
        type: string
      propThree:
        type: string
  required:
    - id
    - propOne
    - propTwo
    - propThree
```

I ran:

```shell
	docker run \
		--mount type=bind,source=./,target=/app \
		protojour/migrado \
		init \
		--schema schema.yml \
		-v strict
```

`migrado` generates the `migrations/` folder and an initial migration as expected, so far so good. In the migration it generates a variable `schema` which is the translation of the YAML file but this variable isn't used anywhere. The schema is duplicated in the call to `db._create`. What is the purpose of this variable?

What I did was remove the duplicate in the `db._create` call and actually reference the `schema` variable instead: `schema.collections.MyCollection`.

Do you think we could update migrado to do the same in the code it generates?
